version: '2.0'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
  api:
    build: backend/
    ports:
      - "5000:5000"
  db:
    build: geo_dataproc/
    image: litter-coalition/geo_dataproc:latest
    environment:
      POSTGRES_DB: postgis
      POSTGRES_USER: trashdev
    expose:
      - "5432"
    ports:
      - "5433:5432" # Exposed to Host on 5433 (for DEV)
    volumes:
      - "./data/raw:/data/raw" # For Persisting MODA Source Data Files...
    