version: '2.0'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - db
  api:
    build: backend/
    ports:
      - "5000:5000"
    env_file:
      - backend/.env


  tileserver:
    image: maptiler/tileserver-gl
    ports:
      - "8080:8080"
    volumes:
      - "./data/layers/:/data/" # For persisting tiles...
    environment:
        config: "./maptiler/config.json"
    command: -p 8080 --verbose

  db:
    build: geo_dataproc/
    image: litter-coalition/geo_dataproc:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: trashdev
    expose:
      - "5432" # Allow other containers to call DB...
    ports:
      - "5433:5432" # Exposed to Host on 5433 (for DEV)
    volumes:
      - "./data/raw:/data/raw" # For Persisting MODA Source Data Files...
      - "./data/layers/:/data/layers/" # For persisting tiles...

